[package]
name = "sgx_backtrace"
version = "1.0.0"
authors = ["MobileCoin"]
edition = "2018"

[lib]
name = "sgx_backtrace"

[features]
default = ["sgx_debug"]

[dependencies]
sgx_enclave_id = { path = "../sgx_enclave_id" }
sgx_libc_types = { path = "../sgx_libc_types" }
sgx_types = { path = "../sgx_types" }
sgx_unwind = { path = "../sgx_unwind" }
sgx_debug = { path = "../sgx_debug", optional = true }
