[package]
name = "sgx_panic"
version = "1.0.0"
authors = ["MobileCoin"]

[lib]
name = "sgx_panic"

[features]
default = ["alloc"]
alloc = []
# Note: One of these two must be selected
panic_abort = []
panic_unwind = ["alloc", "sgx_unwind"]

[dependencies]
sgx_libc_types = { path = "../sgx_libc_types" }
sgx_backtrace = { path = "../sgx_backtrace", optional = true }
sgx_unwind = { path = "../sgx_unwind", optional = true }
