[package]
name = "attest-trusted"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
attest = { path = "../../attest/core", default-features = false }
common = { path = "../../common", default-features = false }
sgx_compat = { path = "../../sgx/sgx_compat" }
sgx_types = { path = "../../sgx/sgx_types" }

failure = { version = "0.1.5", default-features = false, features = ["derive"] }
prost = { version = "0.6.1", default-features = false, features = ["prost-derive"] }
