[package]
name = "build-info"
version = "0.1.0"
authors = ["MobileCoin"]
build = "build.rs"
edition = "2018"

[lib]
name = "build_info"
path = "src/lib.rs"

[[bin]]
name = "show-build-info"
path = "src/bin/main.rs"

[dev-dependencies]
json = "0.12"
