[package]
name = "mcbuild-sgx-utils"
version = "0.2.0"
authors = ["MobileCoin"]
edition = "2018"
description = "SGX utilities assistance, from MobileCoin."
readme = "README.md"

[dependencies]
mcbuild-utils = { path = "../utils" }

cargo-emit = "0.1.1"
cc = "1.0"
failure = { version = "0.1.6", default-features = false }
lazy_static = "1.4"
