[package]
name = "sgx_service"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
sgx_types = { path = "../sgx_types" }

[build-dependencies]
sgx_build = { path = "../sgx_build" }
