[package]
name = "ecies"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
aes-ctr = { version = "0.3.0", default-features = false }
keys = { path = "../../crypto/keys", default-features = false }
hkdf = { version = "0.8.0", default-features = false }
rand_core = { version = "0.5", default-features = false }
sha2 = { version = "0.8", default-features = false }

[dev_dependencies]
test_helper = { path = "../../util/test-helper" }
