[package]
name = "sgx_compat_edl"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
sgx_debug_edl = { path = "../sgx_debug_edl" }
sgx_panic_edl = { path = "../sgx_panic_edl" }

[build-dependencies]
cargo-emit = "0.1"
sgx_debug_edl = { path = "../sgx_debug_edl" }
sgx_panic_edl = { path = "../sgx_panic_edl" }
