[package]
name = "consensus-enclave-edl"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"
links = "consensus_enclave_edl"

[build-dependencies]
mcbuild-utils = { path = "../../../mcbuild/utils" }

cargo-emit = "0.1"
