[package]
name = "consensus-enclave-api"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"
description = """
The ECALL API declarations and API for operating an enclave.
"""

[features]
default = ["std"]
std = [
    "attest/std",
    "attest-ake/std",
    "mcserial/std",
    "serde/std"
]

[dependencies]
attest = { path = "../../../attest/core", default-features = false }
attest-ake = { path = "../../../attest/ake", default-features = false }
attest-enclave-api = { path = "../../../attest/enclave_api", default-features = false }
common = { path = "../../../common", default-features = false }
keys = { path = "../../../crypto/keys", default-features = false }
mcnoise = { path = "../../../crypto/ake/mcnoise", default-features = false }
mcserial = { path = "../../../util/mcserial", default-features = false }
message-cipher = { path = "../../..//crypto/message-cipher" }
sgx_compat = { path = "../../../sgx/sgx_compat" }
transaction = { path = "../../../transaction/core" }

cfg-if = "0.1"
failure = { version = "0.1.5", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
