[package]
name = "consensus-enclave"
version = "1.0.0"
authors = ["MobileCoin"]
edition = "2018"
description = "MobileCoin Consensus Enclave - Application Code"

[dependencies]
attest = { path = "../../attest/core" }
attest-enclave-api = { path = "../../attest/enclave_api" }
common = { path = "../../common" }
consensus-enclave-api = { path = "./api" }
consensus-enclave-edl = { path = "./edl"}
consensus-enclave-measurement = { path = "./measurement" }
enclave-boundary = { path = "../../enclave-boundary" }
keys = { path = "../../crypto/keys" }
mcserial = { path = "../../util/mcserial" }
sgx_backtrace_edl = { path = "../../sgx/sgx_backtrace_edl" }
sgx_debug_edl = { path = "../../sgx/sgx_debug_edl" }
sgx_panic_edl = { path = "../../sgx/sgx_panic_edl" }
sgx_slog = { path = "../../sgx/sgx_slog" }
sgx_slog_edl = { path = "../../sgx/sgx_slog_edl" }
sgx_types = { path = "../../sgx/sgx_types" }
sgx_urts = { path = "../../sgx/sgx_urts" }
transaction = { path = "../../transaction/core" }

[build-dependencies]
mcbuild-sgx-utils = { path = "../../mcbuild/sgx-utils" }
mcbuild-utils = { path = "../../mcbuild/utils" }
cargo-emit = "0.1.1"
