[package]
name = "mclogger-macros"
version = "0.0.1"
authors = ["MobileCoin"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"

[dependencies.proc-macro2]
version = "0.4"
features = ["nightly"]

[dependencies.syn]
version = "0.15"
features = ["full", "extra-traits"]
