[package]
name = "mcbuild-enclave"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"
description = "Enclave build assistance, from MobileCoin."
readme = "README.md"

[dependencies]
mcbuild-utils = { path = "../utils" }
mcbuild-sgx-utils = { path = "../sgx-utils" }
sgx_css = { path = "../../sgx/sgx_css" }

base64 = "0.11"
cargo-emit = "0.1.1"
cargo_metadata = "0.9"
failure = { version = "0.1.6", default-features = false }
rand = "0.7"
rsa = "0.2"
sha2 = "0.8"
